"""Add template table

Revision ID: 78b36ded2558
Revises: 2e736b7c5cd1
Create Date: 2025-06-07 17:31:33.927297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78b36ded2558'
down_revision = '2e736b7c5cd1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('createdBy', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_createdBy'), 'template', ['createdBy'], unique=False)
    op.create_index(op.f('ix_template_id'), 'template', ['id'], unique=False)
    op.create_index(op.f('ix_template_name'), 'template', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_template_name'), table_name='template')
    op.drop_index(op.f('ix_template_id'), table_name='template')
    op.drop_index(op.f('ix_template_createdBy'), table_name='template')
    op.drop_table('template')
    # ### end Alembic commands ### 